# 数据源、视图配置
spring:
 datasource:
   url: jdbc:mysql://localhost:3306/zhjc?useUnicode=true&characterEncoding=utf8&useSSL=false
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver
# mvc:
#   view:
#     prefix: classpath:/templates/, classpath:/static/
#     suffix: .html


#Mybatis扫描
mybatis:
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 8081
  servlet:
    context-path: /ccpx

